name: Generate Sitemap

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly at midnight on Sundays

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1.10.0
        with:
          path-to-root: .  # optional, default is .
          base-url-path: https://sanchit.cc/  # optional, default is https://web.address.of.your.nifty.website/
          include-html: true  # optional, default is true
          include-pdf: true  # optional, default is true
          sitemap-format: xml  # optional, default is xml
          additional-extensions: ''  # optional, default is empty
          drop-html-extension: false  # optional
          date-only: false  # optional
          exclude-paths: ''  # optional, default is empty
