name: Parse and Update HTML

on:
  workflow_dispatch:

jobs:
  parse_html_job:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Fetch and update HTML
        run: |
          API_RESPONSE=$(curl -s https://api.lanyard.rest/v1/users/1189451974043783200)
          NEWDATA=$(echo "$API_RESPONSE" | jq -r '.data.activities[0].state')
          sed -i -E "s@(<!--\\s*look\\s+here\\s+regex!!!\\s*-->)\\s*\"[^\"]*\"@\\1 \"$NEWDATA\"@g" index.html

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update HTML content based on API response" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}