name: Parse and Update HTML

on:
  workflow_dispatch:

jobs:
  parse_html_job:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Fetch and update HTML
        run: |
          # Install a CLI tool or create a Node script
          echo 'const fs = require("fs");' > update.js
          echo 'const https = require("https");' >> update.js
          echo 'const filePath = "index.html";' >> update.js
          echo 'const regex = /<!--\s*look\s+here\s+regex!!!\s*-->"*"/g;' >> update.js
          echo 'https.get("https://api.lanyard.rest/v1/users/1189451974043783200", res => {' >> update.js
          echo '  let body = "";' >> update.js
          echo '  res.on("data", chunk => body += chunk);' >> update.js
          echo '  res.on("end", () => {' >> update.js
          echo '    const newData = JSON.parse(body).someField;' >> update.js
          echo '    let html = fs.readFileSync(filePath, "utf8");' >> update.js
          echo '    // Modify the HTML based on your pattern' >> update.js
          echo '    html = html.replace(regex, newData);' >> update.js
          echo '    fs.writeFileSync(filePath, html, "utf8");' >> update.js
          echo '  });' >> update.js
          echo '});' >> update.js
          node update.js

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update HTML content based on API response" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}